spring.application.name=hoidanit-spring-rest-with-ai

server.port=8081

# 1. Đường dẫn kết nối đến MySQL (URL)
spring.datasource.url=jdbc:mysql://localhost:3307/hr_management?allowPublicKeyRetrieval=true&useSSL=false

# 2. Tài khoản đăng nhập
spring.datasource.username=root
spring.datasource.password=123456

# 3. Khai báo Driver sử dụng cho MySQL 8.0
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Cấu hình Hibernate / JPA (Tự động cập nhật cấu trúc bảng nếu có thay đổi trong code)
spring.jpa.hibernate.ddl-auto=update

# 5. Hiển thị các câu lệnh SQL ra console để tiện theo dõi/debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# secret_key
jwt.secret=hoidanitjwtsecretkeyHS256hoidanitjwtsecretkeyHS256hoidanitjwt

jwt.expiration=86400000